### ISSUE TITLE
Query Parameter example exists rule

### ISSUE THREAD

**Issue by savage-alex** [openapi-contrib/style-guides#10]
Hi,

I have the following rule:
`  adv-query-parameters-example-exists:
    description: All query parameters SHOULD have an example.
    severity: error
    message: 'All query parameters SHOULD have an example.'
    given: "$..parameters[?(@.in == 'query')]"
    then:
      field: example
      function: truthy`
![image](https://user-images.githubusercontent.com/25430683/93067051-a13c2700-f672-11ea-8114-29659f28806d.png)

Which works fine on all but examples that are of type Boolean and value of False. Any ideas?

**Comment by philsturgeon** [comment]
@savage-alex great point!

@p0lip has just added a `defined` core function so you can use that when we get v5.5.1 tagged.

**Comment by savage-alex** [comment]
Kudos for the super fast fix!

**Comment by philsturgeon** [comment]
Spectral v5.6.0 has been released and contains this defined core function.
