### ISSUE TITLE
Allow tests to reference the key in messages to users

### ISSUE THREAD

**Issue by savage-alex** [openapi-contrib/style-guides#11]
As a rule creator (and a consumer of the report)
Verbose messages really help me understand what went wrong with my design:

Given the following rule:
![image](https://user-images.githubusercontent.com/25430683/93092330-34875380-f697-11ea-8d35-2ed5a71ced0e.png)
The consumer is told exactly which parameter has the fault (and the line and ruleset) 
![image](https://user-images.githubusercontent.com/25430683/93092054-d9edf780-f696-11ea-92dc-63b071ade674.png)
Perfect right?

Unfortunately with truthy evaluations for a property it doesn't seem possible to get the key out.
I have tried to include the"hint" {parameter} or {value} in the rule:

Rule using property to pull through:
![image](https://user-images.githubusercontent.com/25430683/93091759-71067f80-f696-11ea-9dae-10d072d503ba.png)
Results in:
![image](https://user-images.githubusercontent.com/25430683/93091818-867ba980-f696-11ea-870c-55c987ec28af.png)

Rule changed to return the value, results in:

![image](https://user-images.githubusercontent.com/25430683/93091676-5207ed80-f696-11ea-88cf-e2994cd36d13.png)

Is it possible we can get the key returned as an option? I think it would be really helpful to consumers

**Comment by philsturgeon** [comment]
This is great feedback. Could you post it on https://github.com/stoplightio/spectral/issues/ 

This repo is used as a collection of useful rules, for now often just as an example of what people could do, and in the future as a simple marketplace of rules.

**Comment by savage-alex** [comment]
Done thanks https://github.com/stoplightio/spectral/issues/1339 sorry for posting in the wrong one.
