### ISSUE TITLE
Clarify license of this repo

### ISSUE THREAD

**Issue by jamietanna** [openapi-contrib/style-guides#16]
As well as being able to personally contribute, I've been discussing about producing a complete set of FHIR rules with my colleagues.

However, before we do, it'd be good to know what the licensing of this repo is, so we can appropriately confirm our contributions will be usable.

**Comment by philsturgeon** [comment]
Answered in #7! You can send PRs here or make a new repo, and feel free to use the rules for whatever. DBAD license. :D
