### ISSUE TITLE
Lerna Monorepo and NPM Releases

### ISSUE THREAD

**Issue by philsturgeon** [openapi-contrib/style-guides#7]
Let's turn this into a monorepo and move the core Spectral OpenAPI and AsyncAPI rulesets over here. 

That will let the community manage them, adding a few new great ideas, removing some we decide we don't like, and generally get them ready for Spectral v6.0 which will come with no-bundled rulesets.

**Comment by jamietanna** [comment]
Is this still a thing planned on the roadmap, Phil? As mentioned in #16 I'd be up for looking at further FHIR rules, but we're also happy doing it in a separate package, as we'd be looking at using a setup similar to https://github.com/co-cddo/api-standards-linting/pull/1 which may not be in line with what we've thought about for this?

**Comment by philsturgeon** [comment]
This is no longer on the roadmap. This repo was an experiment that was meant to mature but now I've switched roles and won't be able to put much time into this repo. If you were willing to make a `spectral-ruleset-fhir` package I'd be more than happy to point people that way.
